### ISSUE TITLE
Get error when trying to package via API in Gulp on Windows 8

### ISSUE THREAD

**Issue by grofit** [maxogden/electron-packager#105]
Whenever I try to run it I just get this error:

```
Packaging app for platform win32 ia32 using electron v0.30.0
path.js:111
      throw new TypeError('Arguments to path.resolve must be strings');
      ^
TypeError: Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:111:13)
    at ncp (blah\node_modules\electron-packager\node_modules\ncp\lib\ncp.js:16:26)
    at Array.operations (blah\node_modules\electron-packager\common.js:82:9)
    at done (blah\node_modules\electron-packager\node_modules\run-series\index.js:13:21)
    at cb (blah\node_modules\electron-packager\node_modules\ncp\lib\ncp.js:255:37)
    at WriteStream.<anonymous> (blah\node_modules\electron-packager\node_modules\ncp\lib\ncp.js:133:14)
    at WriteStream.g (events.js:199:16)
    at WriteStream.emit (events.js:129:20)
    at finishMaybe (_stream_writable.js:484:14)
    at endWritable (_stream_writable.js:493:3)
    at WriteStream.Writable.end (_stream_writable.js:459:5)

```

Running Windows 8.1 pro, electron version 0.30.0 exists (`electron -v` returns that version), it is being used within a gulp task and the options look like:

```
gulp.task("create-package", ["merge-libs", "create-asar"], function(callback) {
    var options = {
        src: "./packaging",
        name: "blah",
        platform: "win32",
        arch: "all",
        version: "0.30.0",
        icon: "resources/blah.ico",
        out: "_packages",
        "app-version": "0.4.5",
        "version-string": {
            "CompanyName": "blah",
            "ProductName": "blah"
        }
    };
    packager(options, function done (err, appPath) {
        if(err) { return console.log(err); }
        callback();
    });
});

```

Any ideas on which bit it is struggling to find? (packaging dir contains the `app.asar` file `_packages` is the output folder.

**Comment by jden** [comment]
Ah, I think I see the problem: instead of `src`, the source directory property on the options object should be `dir`. It's documented [here](https://github.com/maxogden/electron-packager/blob/master/readme.md#packageropts-callback) in the readme, but I think it could be clearer. In the CLI, we check for it as a required argument.

I'd welcome a pull request adding options validation for this for programmatic usage.

**Comment by grofit** [comment]
LOL I cannot believe it is that, I scanned the options many times and didnt pick up on it.. I guess it was my gulp brain expecting everything to be src.
