### ISSUE TITLE
ENOENT when electron-packager tries to package node_modules/.bin

### ISSUE THREAD

**Issue by delvedor** [maxogden/electron-packager#149]
Hi all, when I try to use the electron-packager cli from the command line I get this error:
```
Packaging app for platform win32 x64 using electron v0.33.4

[ { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/asar']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/asar' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/electron-download']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/electron-download' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/extract-zip']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/extract-zip' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/har-validator']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/har-validator' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/mkdirp']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/mkdirp' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/indent-string']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/indent-string' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/ncp']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/ncp' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/nugget']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/nugget' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/pretty-bytes']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/pretty-bytes' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/repeating']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/repeating' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/rimraf']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/rimraf' },
  { [Error: ENOENT: no such file or directory, stat '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/uuid']
    errno: -2,
    code: 'ENOENT',
    syscall: 'stat',
    path: '/Users/delvedor/Development/xxx/yyy/node_modules/.bin/uuid' } ] undefined
```

I’m using **Node v4.1.1**, **npm v2.14.4** and **electron-packager v5.1.0**.
My platform is **MacOS 10.10** and I’m building for Windows, I get the same error if I launch the command inside Windows via Parallels.
I read https://github.com/maxogden/electron-packager/issues/133, but the extract-zip@1.1.1 didn’t solve the problem.

I launch the command via npm-scripts:
   ```json
 "build:win": "electron-packager \"./\" \"software\" --out=\"buildOS/win\" --platform=\"win32\" --arch=\"x64\" --version=\"0.33.4\" --ignore=\"(buildOS|node_modules/electron-builder|jsES6|app/es6|pack.json|README.md)\" app-version=\"3.1.2\" --asar --icon=\"icon.ico\" --version-string.CompanyName=\"xxx\" --version-string.ProductName=\"software" --version-string.FileDescription=\"software\" --version-string.OriginalFilename=\"software\" --version-string.FileVersion=\"3.1.2\" --version-string.ProductVersion=\"3.1.2\" --version-string.LegalCopyright=\"© xxx\"",
```

If I do a grep of extract-zip I get this:
```
delvedor$ npm list | grep extract-zip
│ ├─┬ extract-zip@1.1.1
│ └─┬ extract-zip@1.1.1
```

Not sure, maybe similar to https://github.com/maxogden/electron-packager/issues/146?

**Comment by malept** [comment]
It's probably similar to #146. Given all of the files it's erroring on:
* Do they exist?
* If they exist, are they symlinks?

**Comment by delvedor** [comment]
The *ls -l* inside *node_modules/.bin* folder gives me this:
```
delvedor$ ls -l
total 120
lrwxr-xr-x  1 delvedor  staff  16 Sep 28 19:38 asar -> ../asar/bin/asar
lrwxr-xr-x  1 delvedor  staff  27 Oct  3 16:06 electron -> ../electron-prebuilt/cli.js
lrwxr-xr-x  1 delvedor  staff  26 Oct  3 16:08 electron-builder -> ../electron-builder/cli.js
lrwxr-xr-x  1 delvedor  staff  27 Sep 28 19:38 electron-download -> ../electron-download/cli.js
lrwxr-xr-x  1 delvedor  staff  27 Oct  3 16:07 electron-packager -> ../electron-packager/cli.js
lrwxr-xr-x  1 delvedor  staff  21 Sep 28 19:38 extract-zip -> ../extract-zip/cli.js
lrwxr-xr-x  1 delvedor  staff  34 Sep 28 19:38 har-validator -> ../har-validator/bin/har-validator
lrwxr-xr-x  1 delvedor  staff  23 Sep 28 19:38 indent-string -> ../indent-string/cli.js
lrwxr-xr-x  1 delvedor  staff  20 Sep 28 19:38 mkdirp -> ../mkdirp/bin/cmd.js
lrwxr-xr-x  1 delvedor  staff  14 Sep 28 19:38 ncp -> ../ncp/bin/ncp
lrwxr-xr-x  1 delvedor  staff  16 Sep 28 19:38 nugget -> ../nugget/bin.js
lrwxr-xr-x  1 delvedor  staff  22 Sep 28 19:38 pretty-bytes -> ../pretty-bytes/cli.js
lrwxr-xr-x  1 delvedor  staff  19 Sep 28 19:38 repeating -> ../repeating/cli.js
lrwxr-xr-x  1 delvedor  staff  16 Sep 28 19:38 rimraf -> ../rimraf/bin.js
lrwxr-xr-x  1 delvedor  staff  21 Sep 28 19:38 uuid -> ../node-uuid/bin/uuid
```

**Comment by malept** [comment]
Could you try running electron-packager with this additional argument?

`--ignore "node_modules/\.bin"`

**Comment by delvedor** [comment]
Sure, this is the result:
```
Packaging app for platform win32 x64 using electron v0.33.4
spawn wine ENOEN
...
...
```

**Comment by malept** [comment]
`spawn wine ENOENT` is a different error: https://github.com/maxogden/electron-packager/issues/138#issuecomment-142944815

**Comment by delvedor** [comment]
After I've installed wine all works perfectly.
But if I remove ```node_modules/\.bin``` from the ignore list, the build fails with the same initial error.
Is this a problem/issue?

**Comment by malept** [comment]
I think it's a problem, but I'd like to see if #146 is related before we decide what to do with this GitHub issue (i.e., mark this as duplicate).

**Comment by datnordstrom** [comment]
1+

**Comment by malept** [comment]
FYI, I've created a PR (#186) that adds `node_modules/.bin` to the default ignores.

**Comment by PierBover** [comment]
I'm getting the error too.

> spawn wine ENOENT

I've installed wine using homebrew. I had to install xquartz and a bunch of other dependencies.

I get no other errors...

My build command is:

> electron-packager /Volumes/Data/Projects/Github/xxx/app --platform=win32 --arch=ia32 --version=1.2.2 --out=/Users/pier/Desktop --icon=/Volumes/Data/Projects/Github/xxx/icon.icns

**Comment by malept** [comment]
@PierBover this is a different error than the original problem. Make sure wine exists in your PATH.

**Comment by PierBover** [comment]
Thanks @malept you were right. Wine wasn't properly installed.

**Comment by riccitensor** [comment]
I am packaging an electron app for Windows x64.

```
Packaging app for platform win32 x64 using electron v1.2.2
fs.js:898
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat '/private/tmp/electron-packager/win32-x64/beauty/resources/app/build/elec_as_node/node'
    at Object.fs.statSync (fs.js:898:18)
    at Object.realpathSync (fs.js:1544:12)
```

**Comment by malept** [comment]
@riccitensor this is a completely different problem than this issue. What likely happened is that you downloaded a corrupted prebuilt Electron. Delete the `~/.electron` folder and try again.

**Comment by muneebahmed26301** [comment]
install electron-packager try to check it doc "" https://github.com/electron/electron-packager  ""
then
if anyone is having this kind of err (when you are working on electron Js )
 for eg""
    ENOENT: no such file or directory, link 'C:\softwares\cygwin\tmp\electron-packager\win32-ia32\booker-win32-ia32\electron.exe' -> 'C:\softwares\cygwin\tmp\electron-packager\win32-ia32\booker-win32-ia32\booker.exe'
""
try typing ""npm install electron-packager@12.1.2"" an;d then npx electron-packager . or npx electron-packager .

![Annotation 2020-03-06 171054](https://user-images.githubusercontent.com/32039227/76082557-7f7c2c00-5fcd-11ea-844a-cf2dc53364f8.png)

**Comment by malept** [comment]
@muneebahmed26301 your `icon.ico` is not in the correct Windows ICO format.

This problem is not related to this issue, if you need more assistance, please use one of the [community forums](https://electronjs.org/community).
