### ISSUE TITLE
Not able to compile for Windows on Mac

### ISSUE THREAD

**Issue by ValentinCreative** [maxogden/electron-packager#159]
Hi, 

I'm on osx 10.11 (but tested with 10.10, same issue)
Node v4.2.0
Electron-packager v5.1.0

when I do this command 

`electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0` 

I got this error 

```sh
Packaging app for platform win32 x64 using electron v0.33.3
spawn wine ENOENT

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "run" "win"
npm ERR! node v4.2.0
npm ERR! npm  v2.12.1
npm ERR! code ELIFECYCLE
npm ERR! Legallais@1.0.0 win: `electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Legallais@1.0.0 win script 'electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0'.
npm ERR! This is most likely a problem with the Legallais package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0
npm ERR! You can get their info via:
npm ERR!     npm owner ls Legallais
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/v_leveque/Sites/legallais-box/npm-debug.log
```

My npm log 

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/4.2.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'win' ]
2 info using npm@2.12.1
3 info using node@v4.2.0
4 verbose run-script [ 'prewin', 'win', 'postwin' ]
5 info prewin Legallais@1.0.0
6 info win Legallais@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info Legallais@1.0.0 Failed to exec win script
9 verbose stack Error: Legallais@1.0.0 win: `electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:818:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid Legallais@1.0.0
11 verbose cwd /Users/v_leveque/Sites/legallais-box
12 error Darwin 15.0.0
13 error argv "/usr/local/Cellar/node/4.2.0/bin/node" "/usr/local/bin/npm" "run" "win"
14 error node v4.2.0
15 error npm  v2.12.1
16 error code ELIFECYCLE
17 error Legallais@1.0.0 win: `electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0`
17 error Exit status 1
18 error Failed at the Legallais@1.0.0 win script 'electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0'.
18 error This is most likely a problem with the Legallais package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron-packager ./ Legallais --out ./release --icon ./icons/win/legallais-Icon.png --platform=win32 --arch=x64 --version=0.33.3 --app-version=1.0.0
18 error You can get their info via:
18 error     npm owner ls Legallais
18 error There is likely additional logging output above.
```

**Comment by ValentinCreative** [comment]
Finally found the issue. 
When compiling for windows the argument "--icon" causes this error.

**Comment by byenow** [comment]
@ValentinCreative 
You are right, when I remove the "--icon", it works !

**Comment by malept** [comment]
Yes, please see the section *[Building Windows apps from non-Windows platforms](https://github.com/electron-userland/electron-packager/blob/master/readme.md#building-windows-apps-from-non-windows-platforms)* in the readme for why this is the case.
