### ISSUE TITLE
Unable to package app with native modules

### ISSUE THREAD

**Issue by photex** [maxogden/electron-packager#192]
I have an app that's using a native module (nanomsg) and while I can run it using electron, when I try to package it I get the following exception at startup.

```
Uncaught Exception:
Error: Could not locate the bindings file. Tried:
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/build/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/build/Debug/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/build/Release/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/out/Debug/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/Debug/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/out/Release/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/Release/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/build/default/node_nanomsg.node
 → /projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/compiled/4.1.1/darwin/x64/node_nanomsg.node
    at bindings (/projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/node_modules/nanomsg/lib/index.js:1:119)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/projects/ixtools/Source/ixl/build/ix3dLauncher-darwin-x64/ix3dLauncher.app/Contents/Resources/app/dist/app.js:7:12)
    at Module._compile (module.js:434:26)
```

Running `find . -type f -name 'node_nanomsg.node'` I see that only the original is present. How can I force the native modules to be included? I've tried with and without pruning.

**Comment by photex** [comment]
Ok, please disregard, I discovered that this was related to an incorrect ignore regex.
