### ISSUE TITLE
When opening linux binary, a SyntaxError occurs

### ISSUE THREAD

**Issue by steebchen** [maxogden/electron-packager#249]
This is how I built it:
```
> ~/Documents/projects/MyApp/app $ electron-packager . --platform=linux --arch=all
Downloading electron-v0.36.7-linux-ia32.zip
[============================================>] 100.0% of 38.4 MB (1.32 MB/s)
Packaging app for platform linux ia32 using electron v0.36.7
Packaging app for platform linux x64 using electron v0.36.7
Wrote new apps to:
/home/luca/Documents/projects/MyApp/app/MyApp-linux-ia32
/home/luca/Documents/projects/MyApp/app/MyApp-linux-x64
```

When I run the binary, regardless of the 32/64 version, nothing happens. When running from the console, this error appears:
```
> ~/Documents/projects/MyApp/app/MyApp-linux-x64 $ ./MyApp 
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/home/luca/Documents/projects/MyApp/app/MyApp-linux-x64/resources/atom.asar/browser/lib/init.js:152:8)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by malept** [comment]
Does it work with an older version of Electron?

**Comment by steebchen** [comment]
I tried some versions earlier, which didn't work either.

With version v0.34.4, the following error occurred:
```
luca@LucaPC ~/Documents/projects/EasyScreenshot/out/EasyScreenshot-linux-x64 $ ./EasyScreenshot 
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Object.<anonymous> (/home/luca/Documents/projects/EasyScreenshot/out/EasyScreenshot-linux-x64/resources/atom.asar/browser/lib/init.js:125:10)
    at Object.<anonymous> (/home/luca/Documents/projects/EasyScreenshot/out/EasyScreenshot-linux-x64/resources/atom.asar/browser/lib/init.js:127:4)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
```
Still testing with other versions.

**Comment by malept** [comment]
Just to be thorough, have you also syntax-checked your JavaScript files? (You can do so by running `node -c $javascript_file`.)

**Comment by steebchen** [comment]
```
~/Documents/projects/EasyScreenshot $ node -c app/background.js 
node: bad option: -c
```

**Comment by malept** [comment]
Hmm. What version of node are you using? It might have been added in a more recent version. (I'm currently running v5.5.0.)

**Comment by steebchen** [comment]
Ok, updated to v5.5.0, here is the output:
```
~/Documents/projects/EasyScreenshot $ node -c app/app.js
/home/luca/Documents/projects/EasyScreenshot/app/app.js:7
import os from 'os'; // native node.js module
^^^^^^

SyntaxError: Unexpected token import
    at startup (node.js:113:11)
    at node.js:999:3
```

**Comment by malept** [comment]
According to the [Node.js documentation](https://nodejs.org/en/docs/es6/), ES6 modules are not a "stable" feature of V8 (the JavaScript engine that currently powers Node.js), so I don't think you can use that syntax currently.

Closing, as this issue is not specific to electron-packager.

**Comment by steebchen** [comment]
Ok, thanks for the great help. I was using a starter template where ES6 was used, found another way to compile it.

**Comment by ac-opensource** [comment]
@steebchen how?

**Comment by malept** [comment]
My educated guess is by using babel.

**Comment by steebchen** [comment]
I don't remember anymore, but I think I simply used another starter
template. Babel would probably a solution too.

Mark Lee <notifications@github.com> schrieb am Di., 17. Mai 2016 15:45:
