### ISSUE TITLE
Built binary on Mac does not start

### ISSUE THREAD

**Issue by radiospiel** [maxogden/electron-packager#254]
I am trying to build electron-quick-start into a mac binary. I am running:

electron-packager . FooBar --platform=darwin --arch=x64 --version=0.28.2

which gives me a .app folder; yet when I try to run it it complains that:

```
Uncaught Exception:
Error: Cannot find module 'electron'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/eno/projects/mpx-devbox/projects/no-cockpit/electron-quick-start/FooBar-darwin-x64/FooBar.app/Contents/Resources/app/main.js:3:18)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Object.<anonymous> (/Users/eno/projects/mpx-devbox/projects/no-cockpit/electron-quick-start/FooBar-darwin-x64/FooBar.app/Contents/Resources/atom.asar/browser/lib/init.js:104:10)
```

at which point I am totally lost.

**Comment by malept** [comment]
According to the Electron release notes, the `electron` module was introduced in [version 0.35.0](https://github.com/atom/electron/releases/tag/v0.35.0). You should use at least that version to package Electron (though, I would suggest using the most recent version since you're just starting out).

**Comment by radiospiel** [comment]
Thank you for that superquick response :) From what I understand I am using "electron-prebuilt": "^0.36.0"

I put up the entire project here: https://github.com/radiospiel/electron-quick-start and would be supergrateful if you or someone who knows more could have a look..

**Comment by radiospiel** [comment]
after poking around and understanding that --version describes the electron version to use and not the app version to build, I finally got it :)
