### ISSUE TITLE
Windows Build ENOENT Error.

### ISSUE THREAD

**Issue by delvedor** [maxogden/electron-packager#64]
Hi, I'm trying to build my app for windows from a mac.
These are my scripts, the Electron-packager version is 4.1.2:
```javascript
"build-mac": "electron-packager ./ MyApp --platform=darwin --arch=x64 --version=0.28.1"
"build-win": "electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.28.1"
"build-win": "electron-packager ./ MyApp --platform=win32 --arch=ia32 --version=0.28.1"
```
The build for mac goes right, contrariwise both the builds for Windows gave me this error (just change the arch with x64, I modified slightly the output by masking directory paths):
```
Geyser:MyApp delvedor$ npm run-script build-win

> myapp@3.1.0 build-win /.../.../MyApp
> electron-packager ./ MyApp --platform=win32 --arch=ia32 --version=0.28.1

Downloading electron-v0.28.1-win32-ia32.zip
[=================================================>] 100.0% of 38.79 MB (1.12 MB/s)
Packaging app for platform win32 ia32 using electron v0.28.1
[ { [Error: ENOENT, stat '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Libraries/Libraries' },
  { [Error: ENOENT, stat '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/Current/Libraries/Libraries' },
  { [Error: ENOENT, stat '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries']
    errno: -2,
    code: 'ENOENT',
    path: '/.../.../MyApp.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/Libraries' } ] undefined

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "run-script" "build-win"
npm ERR! node v0.12.0
npm ERR! npm  v2.7.6
npm ERR! code ELIFECYCLE
npm ERR! myapp@3.1.0 build-win: `electron-packager ./ MyApp --platform=win32 --arch=ia32 --version=0.28.1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myapp@3.1.0 build-win script 'electron-packager ./ MyApp --platform=win32 --arch=ia32 --version=0.28.1'.
npm ERR! This is most likely a problem with the myapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron-packager ./ MyApp --platform=win32 --arch=ia32 --version=0.28.1
npm ERR! You can get their info via:
npm ERR!     npm owner ls myapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!    /.../.../MyApp/npm-debug.log
```

And this is the npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run-script', 'build-win' ]
2 info using npm@2.7.6
3 info using node@v0.12.0
4 verbose run-script [ 'prebuild-win', 'build-win', 'postbuild-win' ]
5 info prebuild-win myapp@3.1.0
6 info build-win myapp@3.1.0
7 verbose unsafe-perm in lifecycle true
8 info myapp@3.1.0 Failed to exec build-win script
9 verbose stack Error: myapp@3.1.0 build-win: `electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.28.1`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:14:12)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1008:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
10 verbose pkgid myapp@3.1.0
11 verbose cwd /../../MyApp
12 error Darwin 14.3.0
13 error argv "node" "/usr/local/bin/npm" "run-script" "build-win"
14 error node v0.12.0
15 error npm  v2.7.6
16 error code ELIFECYCLE
17 error myapp@3.1.0 build-win: `electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.28.1`
17 error Exit status 1
18 error Failed at the myapp@3.1.0 build-win script 'electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.28.1'.
18 error This is most likely a problem with the myapp package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.28.1
18 error You can get their info via:
18 error     npm owner ls myapp
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
```

**Comment by malept** [comment]
It sounds like you need to ignore the output directories for previously generated packages. For example, add `--ignore=MyApp.app`.

**Comment by delvedor** [comment]
It works, thank you!

**Comment by kylebrowning** [comment]
@malept This is still broken if you add an icon file!
```
electron-packager ./ Report --platform=all --arch=x64 --version=0.31.1 --ignore=Report.app --overwrite --out=app --icon=docicon.icns
Packaging app for platform darwin x64 using electron v0.31.1
Packaging app for platform linux x64 using electron v0.31.1
Packaging app for platform win32 x64 using electron v0.31.1
spawn wine ENOENT

electron-packager ./ Report --platform=all --arch=x64 --version=0.31.1 --ignore=app --overwrite --out=app --icon=docicon.icns
Packaging app for platform darwin x64 using electron v0.31.1
Packaging app for platform linux x64 using electron v0.31.1
Packaging app for platform win32 x64 using electron v0.31.1
spawn wine ENOENT
```

**Comment by kylebrowning** [comment]
Same thing as before, just using the command originally in this ticket and adding my icon file.

```
electron-packager ./ MyApp --platform=win32 --arch=x64 --version=0.31.1 --ignore=MyApp.app --overwrite --icon=docicon.icns
Packaging app for platform win32 x64 using electron v0.31.1
spawn wine ENOENT
```

**Comment by kylebrowning** [comment]
cc @maxogden

**Comment by malept** [comment]
@kylebrowning this is a different problem.

> `spawn wine ENOENT`

This means that you do not have [Wine](https://www.winehq.org) installed.

**Comment by kylebrowning** [comment]
@malept Thanks for clarification.
